export const CONFIG = {
	WIDTH: 1300,
	HEIGHT: 640,
	TILE_SIZE: 32,
	FRAME_SIZE: 32,
	PACMAN_SPEED: 200,
	WIDTH_TILES: 28,
	HEIGHT_TILES: 20,
};

export const SCENES = {
	BOOT: 'BOOT_SCENE',
	GAME: 'GAME_SCENE'
};
export const SPRITES = {
	PACMAN: 'PACMAN_SPRITE',
	GHOST: 'GHOST_SPRITE',
	DOT: 'DOT_SPRITE',
	CANDY: 'CANDY_SPRITE'
};
export const TILESETS = {
	TILESMAP: 'TILESMAP'
};
export const TILEMAPS = {
	LEVEL: 'LEVEL_TILEMAP'
};
export const ANIMATIONS = {
	PACMAN: 'PACMAN_ANIMATION',
	GHOST: 'GHOST_LEFT_ANIMATION',
};
export const DIRECTIONS = {
	LEFT: 0,
	UP: 90,
	RIGHT: -180,
	DOWN: -90
};
